### ISSUE TITLE
Table of contents "children:" entries inherit sibling's external URL hostname 

### ISSUE THREAD

**Issue by mbland** [mbland/jekyll-theme-guides-mbland#13]
Apparently when the first child of a table of contents entry points to an external URL, the remaining child entries will contain links with the base host URL injected, leading to broken links.

In other words, this:
```yaml
navigation:
- text: Parent
  url: parent/
  internal: true
  children:
  - text: External
    url: https://external.example.org/foo
    internal: false
  - text: Child
    url: child/
    internal: true
```

Should produce:
```
/parent/child/
```

but instead produces:
```
/parent/https://external.example.org/child/
```

@paragbhagwat noticed this issue in one of our internal Cvent documents.
